{% set name = "libzen" %}
{% set version = "0.4.41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MediaArea/ZenLib/archive/v{{ version }}.tar.gz
  sha256: 45d5173fa0278f5264daa6836ae297aa303984482227d00b35c4f03929494c8f

build:
  number: 1
  run_exports:
    # There is no ABI history for this library
    # I am going to err on the side of caution to avoid repodata patching.
    - {{ pin_subpackage(name, max_pin="x.x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config

test:
  commands:
    - test -f ${PREFIX}/lib/libzen.dylib  # [osx]
    - test -f ${PREFIX}/lib/libzen.so     # [linux]
    - test -f ${PREFIX}/include/ZenLib/Utils.h  # [unix]
    - IF NOT EXIST %LIBRARY_LIB%/zen.lib exit 1  # [win]
    - IF NOT EXIST %LIBRARY_INC%/ZenLib/Utils.h exit 1  # [win]

about:
  home: https://mediaarea.net
  license: Zlib
  license_file: License.txt
  summary: Small C++ derivate classes to have an easier life

  dev_url: https://github.com/MediaArea/ZenLib

extra:
  recipe-maintainers:
    - anjos
    - sodre
    - pavelzw
